### ISSUE TITLE
How to implement  this solution

### ISSUE THREAD

**Issue by hananaq** [ichdasich/bbb-rec-perm#1]
i want to implement you solution to my BBB server to protect the recordings from being accessed without permission  but im new in this field, can you walk me through how to implement it, where to put the files ?

**Comment by ichdasich** [comment]
I currently do not really have the resources to provide consulting. But I will put "Update documentation" on my todo, and will also throw in some more pointers to reading resources etc.; Probably somewhen later today.

**Comment by what-ri** [comment]
Hi IchDasIch,

Approximate guideline/instructions how to implement your solution would be amazing!
Thank you for your time & helping out hundreds of users who are concerned about security.

**Comment by what-ri** [comment]
1. Git clone the latest greenlite IchDasIch fork
`git clone -b rec_restrictions https://github.com/ichdasich/greenlight.git`

* Updated above line as instructed in the post below

2. Compile it with docker / run it - follow the Customize install instructions from BBB page

3. Git clone rec-perm
`git clone https://github.com/ichdasich/bbb-rec-perm`

4. Install fcgiwrap if it's missing
`apt-get install fcgiwrap`

5. Install bcrypt
`apt-get install python3-bcrypt`

6. Install psycopg
`apt-get install python3-psycopg2`

If you are using out of the box bbb without scalelite - you only need auth-passwd-bbb.py (rename it to auth.py)
Edit the auth.py script as suggested by anrxc in the other issue posted.
Edit you postgresql password to reflect .env file in /root/greenlight/ - out of the box "password" with lower case.

7. Edit your nginx config (attached example)
[bigbluebutton.conf.txt](https://github.com/ichdasich/bbb-rec-perm/files/4806838/bigbluebutton.conf.txt)

8. Replace BBB.nginx files in /etc/bigbluebutton/nginx
cp /bbb-rec-perm/nginx-conf/etc/bigbluebutton/nginx/* /etc/bigbluebutton/nginx

9. Edit your path to error page in these files

Thank you for the great script!

**Comment by ichdasich** [comment]
uhm, whatever you do, do not use the custom-26a/custom-changes; These have changes specific to my infrastructure/setup. ;-)

You should use https://github.com/ichdasich/greenlight/tree/rec_restrictions and merge that with the current upstream branch you want to use. I will update that branch to the current tag in a bit.

Apart from that: Mind if I use the documentation you just wrote in README.md?

**Comment by what-ri** [comment]
Sure, go ahead.

**Comment by ichdasich** [comment]
Added documentation. Closing this. Thanks again!
