### ISSUE TITLE
Not bieng able to include bbb-rec-perm in BBB 2.3

### ISSUE THREAD

**Issue by human-bieng** [ichdasich/bbb-rec-perm#11]
Hello there
I tried to follow installation instructions but failed to prevent watching playback urls from outside BBB
What could be the reason for failed to use it !!
Any help will be appreciated
Thanks in advance

**Comment by ichdasich** [comment]
IIRC BBB 2.3 changed the player used for recordings, so some things might be different. I was planning to toy around with BBB 2.3 over the end of the year; In case I get around to it, i'll update bbb-rec-perm to support 2.3.

**Comment by ichdasich** [comment]
So, i have BBB2.3 in prod now, and did in fact not change anything to get it running; Matching for the new URLs seems to still work fine. Closing hence.
