### ISSUE TITLE
ImportError: BeautifulSoup 

### ISSUE THREAD

**Issue by fnord235** [ichdasich/bbb-rec-perm#12]
Hey there,
first of all, I'd like to say thank you :) I finally managed to get it up and running, but it has been quite a journey to get to this point.

A couple of weeks ago it took me ages to fix the image_build script, because my version still contained the yanked mimemagic package. I was quite happy that it seems to be fixed now, because I added this feature to another BigBlueButton server today, and the script ran through this time without any issues.  

Am I missing something, or is it normal that I had to install BeautifulSoup via pip manually? Before doing so, I had this kind of error message in /var/log/nginx.error several times, there were no thumbnails in greenlight's recording list, and trying to access the record via BBB's playback failed with an internal server error: 
 
2021/05/06 15:08:54 [error] 25690#25690: *208 FastCGI sent in stderr: "Traceback (most recent call last):
  File "/var/www/html/gl-auth/auth.py", line 7, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named 'bs4'" while reading response header from upstream ...

Now that I have manually installed BeautifulSoup, it works like a charm. I didn't fiddle around with virtualenv or something, do you think this might be a security problem when going to production?
Since I had to do this on both servers to get it working, it seems worth mentioning in the installation guide, because it took me a couple of days the first time I tried to install this. 

Thanks for this great feature! Although it obviously can't fix what's wrong with BBB itself (like this guessable url stuff, once the meeting id has been provided via sharing the playback link - only 9 digits left to guess) - it is definitely an advantage being able to mark records as private.  
 
Looking forward to hearing from you,
fnord235

**Comment by ichdasich** [comment]
Heho,
thanks for pointing this out. I adjusted the documentation. Instead of installing it via pip, you should do an `apt-get install python3-bs4`.

Related: You can also use the extended version of rec-perm that allows you to authenticate recordings against your greenlight user database (if you are not using a form of remote users). That is probably even a bit better than just setting recordings to private. :-)
