### ISSUE TITLE
Cookie upon login

### ISSUE THREAD

**Issue by what-ri** [ichdasich/bbb-rec-perm#4]
Hi IchDasIch,

Would it be possible to script in the cookie session, so users don't have to login every time when they close/open the browser?
Thanks once more for the great script!

**Comment by ichdasich** [comment]
Can you elaborate what you mean? Setting a cookie for the script itself, or using the GL cookie? The latter will be difficult with scalelite setups (different subdomain).

**Comment by ichdasich** [comment]
So chewing on this a little, I think it can not be (easily) implemented. This all works around basic auth in nginx. This means that the client does not directly see output from the script (which is just an auth hook in nginx). This means that there is no option to set a cookie; This would have to happen in the disaplyed content (the media player) which is, however, static. While I like your suggestion, i think it is out of scope for this script. A cleaner sollution would most likely be a feature that adds the ability to the player to utilize frontend authentication cookies (from e.g. greenlight); However, that would be a whole different implementation.
